### ISSUE TITLE
Setup a demo site

### ISSUE THREAD

**Issue by yonas** [bewcloud/bewcloud#1]
Would be great to play with an online demo.

**Comment by BrunoBernardino** [comment]
Thanks! Once I have Contacts / CalDav in I'll probably look into it

**Comment by Joly0** [comment]
> Thanks! Once I have Calendar / CalDav and Files / WebDav in, I'll probably look into it.

Do you have any rough timeframe, on how long you will need to get files working? Dont want you to rush anything, though i am very interested in this project an really looking forward for this feature :)

**Comment by BrunoBernardino** [comment]
@Joly0 No clue, this is a side project and I might have days with lots of time and weeks without any. Right now, CardDav and CalDav are mostly working, but there are many (complex) features in CalDav that make it not a real alternative to Nextcloud, and I'm evaluating if I want to chase that complexity or ditch CardDav + CalDav for something like [Radicale](https://radicale.org/v3.html) and focus in Files instead, since that's where there are less options available (especially good servers with good sync and sharing options).

That being said, I am very motivated to figure that out and "delete" my two Nextcloud instances, so I'd figure that in a couple of months there should be _something_.

**Comment by Joly0** [comment]
@BrunoBernardino Thanks for your quick answer and insight in your doing. I am currently running filerun, but i am looking for something to switch to. Nextcloud is very bloated imo and has many unneeded features which are sometimes not that easy to deactivate. I am really searching for a good alternative, which might also have an integration with open office. But simply a fast and slim alternative to nextcloud files is all i am searching for. All other alternatives dont look that promising, but yours does

**Comment by BrunoBernardino** [comment]
@Joly0 thank you for the kind words!

**Comment by BrunoBernardino** [comment]
@Joly0 basic files CRUD is here now, but there's still no sharing or syncing, and that will certainly take a while to build.

**Comment by BrunoBernardino** [comment]
I'm doing sharing via symlinks for now after realizing other ways were getting too complicated (#4 and that it's enough for me), so syncing is coming up next. I must say the search is already much faster and more useful than Nextcloud's for me (it's using `find` and `grep`).

**Comment by BrunoBernardino** [comment]
FYI a WebDav server is now fully working, so you can use `rclone` (what I'll be leveraging for the desktop and mobile sync clients I'm working on next) or many other tools to sync/interact.

**Comment by BrunoBernardino** [comment]
I've decided I won't do this, now that #5 implemented an easy way to quickly test this locally with the `docker-compose.yml` file and the automatically built image. That combined with the demo videos every month and the screenshots on the homepage that exist now, should be enough.

I don't want to have to build and maintain a demo version with limitations and concerns about privacy and abuse, sorry.
